// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AnyTopic.Data.Entities
{
    [Table("Message", Schema = "signalr")]
    public partial class Message
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("FromUserID")]
        public int FromUserId { get; set; }
        [Column("ToRoomID")]
        public int ToRoomId { get; set; }
        [Required]
        public string Content { get; set; }
        [Precision(0)]
        public DateTimeOffset Timestamp { get; set; }

        [ForeignKey("ToRoomId")]
        [InverseProperty("Message")]
        public virtual Room ToRoom { get; set; }
    }
}