// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AnyTopic.Data.Entities
{
    [Table("Room", Schema = "signalr")]
    public partial class Room
    {
        public Room()
        {
            Message = new HashSet<Message>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("AdminID")]
        public int AdminId { get; set; }

        [InverseProperty("ToRoom")]
        public virtual ICollection<Message> Message { get; set; }
    }
}